version: '3.7'

networks:
  redis:
    driver: bridge

services:
  redis-master:
    image: redis:latest
    hostname: redis-master
    networks:
      - redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    ports:
      - 6379:6379
    command: --port 6379
  redis-slave1:
    image: redis:latest
    hostname: redis-slave1
    networks:
      - redis
    ports:
      - 6378:6378
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    depends_on:
      - redis-master
    command: --port 6378 --replicaof redis-master 6379
  redis-slave2:
    image: redis:latest
    hostname: redis-slave2
    networks:
      - redis
    ports:
      - 6377:6377
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    depends_on:
      - redis-master
    command: --port 6377 --replicaof redis-master 6379
