version: '3.7'

networks:
  redis:
    driver: bridge

services:
  redis-1:
    image: redis:latest
    hostname: redis-1
    networks:
      - redis
    ports:
      - 7000:7000
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf --port 7000
  redis-2:
    image: redis:latest
    hostname: redis-2
    networks:
      - redis
    ports:
      - 7001:7001
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf --port 7001
  redis-3:
    image: redis:latest
    hostname: redis-3
    networks:
      - redis
    ports:
      - 7002:7002
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf --port 7002
  redis-4:
    image: redis:latest
    hostname: redis-4
    networks:
      - redis
    ports:
      - 7003:7003
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf --port 7003
  redis-5:
    image: redis:latest
    hostname: redis-5
    networks:
      - redis
    ports:
      - 7004:7004
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf --port 7004
  redis-6:
    image: redis:latest
    hostname: redis-6
    networks:
      - redis
    ports:
      - 7005:7005
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf --port 7005
  redis-cluster-setup:
    image: redis:latest
    networks:
      - redis
    restart: "no"
    entrypoint: ["bash", "-c", "sleep 5 & redis-cli --cluster create redis-1:7000 redis-2:7001 redis-3:7002 redis-4:7003 redis-5:7004 redis-6:7005 --cluster-replicas 1 --cluster-yes"]
    depends_on:
      - redis-1
      - redis-2
      - redis-3
      - redis-4
      - redis-5
      - redis-6

