version: '3.7'

networks:
  redis:
    driver: bridge

services:
  redis-1:
    image: &docker_image redis:latest
    hostname: redis-1
    networks: &networks
      - redis
    ports:
      - 7000:7000
    volumes: &volumes
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf
  redis-2:
    image: *docker_image
    hostname: redis-2
    networks: *networks
    ports:
      - 7001:7000
    volumes: *volumes
    command: redis-server /usr/local/etc/redis/redis.conf
  redis-3:
    image: *docker_image
    hostname: redis-3
    networks: *networks
    ports:
      - 7002:7000
    volumes: *volumes
    command: redis-server /usr/local/etc/redis/redis.conf
  redis-4:
    image: *docker_image
    hostname: redis-4
    networks: *networks
    ports:
      - 7003:7000
    volumes: *volumes
    command: redis-server /usr/local/etc/redis/redis.conf
  redis-5:
    image: *docker_image
    hostname: redis-5
    networks: *networks
    ports:
      - 7004:7000
    volumes: *volumes
    command: redis-server /usr/local/etc/redis/redis.conf
  redis-6:
    image: *docker_image
    hostname: redis-6
    networks: *networks
    ports:
      - 7005:7000
    volumes: *volumes
    command: redis-server /usr/local/etc/redis/redis.conf
  redis-cluster-setup:
    image: *docker_image
    networks: *networks
    restart: "no"
    entrypoint: ["bash", "-c", "sleep 5 & redis-cli --cluster create redis-1:7000 redis-2:7000 redis-3:7000 redis-4:7000 redis-5:7000 redis-6:7000 --cluster-replicas 1 --cluster-yes"]
    depends_on:
      - redis-1
      - redis-2
      - redis-3
      - redis-4
      - redis-5
      - redis-6

